//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalizationResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmployeeSurvey.LocalizationProvider.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to БГ.
        /// </summary>
        public static string CultureBG {
            get {
                return ResourceManager.GetString("CultureBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        public static string CultureEN {
            get {
                return ResourceManager.GetString("CultureEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current position.
        /// </summary>
        public static string EmployeeCurrentPosition {
            get {
                return ResourceManager.GetString("EmployeeCurrentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmployeeEmail {
            get {
                return ResourceManager.GetString("EmployeeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years of experience.
        /// </summary>
        public static string EmployeeExperienceYears {
            get {
                return ResourceManager.GetString("EmployeeExperienceYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string EmployeeNameFirst {
            get {
                return ResourceManager.GetString("EmployeeNameFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string EmployeeNameLast {
            get {
                return ResourceManager.GetString("EmployeeNameLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known languages (select between 1 and 5).
        /// </summary>
        public static string LabelProgLanguagePanel {
            get {
                return ResourceManager.GetString("LabelProgLanguagePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seniority level.
        /// </summary>
        public static string LabelSeniorityLevel {
            get {
                return ResourceManager.GetString("LabelSeniorityLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a level.
        /// </summary>
        public static string SeniorityLevelDefault {
            get {
                return ResourceManager.GetString("SeniorityLevelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junior.
        /// </summary>
        public static string SeniorityLevelJunior {
            get {
                return ResourceManager.GetString("SeniorityLevelJunior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid.
        /// </summary>
        public static string SeniorityLevelMid {
            get {
                return ResourceManager.GetString("SeniorityLevelMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior.
        /// </summary>
        public static string SeniorityLevelSenior {
            get {
                return ResourceManager.GetString("SeniorityLevelSenior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey statistics.
        /// </summary>
        public static string TitlePageStatisticsIndex {
            get {
                return ResourceManager.GetString("TitlePageStatisticsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New survey.
        /// </summary>
        public static string TitlePageSurveyNew {
            get {
                return ResourceManager.GetString("TitlePageSurveyNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee experience survey.
        /// </summary>
        public static string TitleWebSite {
            get {
                return ResourceManager.GetString("TitleWebSite", resourceCulture);
            }
        }
    }
}
